### ISSUE TITLE
Change source map path on published extensions

### ISSUE THREAD

**Issue by BasixKOR** [FormidableLabs/urql-devtools#100]
The source map of urql-devtools is not disabled in Firefox extensions.

**Comment by andyrichardson** [comment]
@BasixKOR I'm not too sure what the issue is here, are you able to expand?

**Comment by BasixKOR** [comment]
![image](https://user-images.githubusercontent.com/7413880/73592335-74505f00-453c-11ea-9124-c85ab4649aa6.png)

When urql-devtools is enabled in Firefox, Firefox debugger shows Webpack root in Sources tab. These files are mixed with other project source if opened in Webpack source-map enabled websites (commonly project in development).

**Comment by andyrichardson** [comment]
Thanks for the screenshot @BasixKOR - that helps!

There's a discussion on [how to change this in webpack](https://github.com/webpack/webpack/issues/3603#issuecomment-357664819). I'll give it a shot some time in the near future.
