### ISSUE TITLE
svelte: not possible to use with Svelte

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql-devtools#163]
It is not possible to use with Svelte today I guess_

`Uncaught TypeError: Failed to resolve module specifier "react". Relative references must start with either "/", "./", or "../".`

![image](https://user-images.githubusercontent.com/41120635/79783364-d7ce7980-8340-11ea-9b9f-73efe41abd78.png)

**Comment by JoviDeCroock** [comment]
This will be fixed in the next release for preact and svelte

**Comment by andyrichardson** [comment]
Thanks for the issue! As @JoviDeCroock  said, a fix is coming soon!

CC: https://github.com/FormidableLabs/urql-devtools-exchange/issues/25
