### ISSUE TITLE
Add animations for incoming events

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#27]
Animations for new events should be swift and communicate a downwards push on the list.

This animation should not occur when events appear in the list after a change of filtering rules.

**Comment by JoviDeCroock** [comment]
I think this issue can be closed?

**Comment by andyrichardson** [comment]
@JoviDeCroock - yeah let's close it. 

Fixed by #49

Animations/events were in the wrong order last I checked but that's another issue we can sort later.
