### ISSUE TITLE
Remove truncation on the exporer view

### ISSUE THREAD

**Issue by kadikraman** [FormidableLabs/urql-devtools#287]
On the explorer view, some of the data gets truncated regardless of how much space there is to display it. It’s be great to see the whole JSON, or at the very least have an option to expand to see everything.

![Screenshot 2020-08-18 at 12 04 14](https://user-images.githubusercontent.com/6534400/90507155-57345400-e14d-11ea-8d83-9b402fc6085d.png)

**Comment by andyrichardson** [comment]
Thanks for the issue @kadikraman!

> at the very least have an option to expand to see everything

This definitely needs work - there's no need for truncation here! 

FYI - It's not very obvious at the moment but that "Arguments" section in the info pane has the full arguments.
