### ISSUE TITLE
Add a new line between description and query names

### ISSUE THREAD

**Issue by kadikraman** [FormidableLabs/urql-devtools#288]
On the bottom right corner of the request pane, the descriptions of the fields and the field type are displayed on the same line, making it not very easy to red. It might be nicer if the definitions would be be on a separate line.

![Screenshot 2020-08-18 at 12 02 32](https://user-images.githubusercontent.com/6534400/90507462-d6c22300-e14d-11ea-8bcc-087b4c201331.png)

**Comment by andyrichardson** [comment]
Good catch!

**Comment by r281GQ** [comment]
Added a pr in #321 .

**Comment by andyrichardson** [comment]
Fixed! Thanks @r281GQ
