### ISSUE TITLE
A cache-only query crashes the devtools if the query is not already cached

### ISSUE THREAD

**Issue by vitosamson** [FormidableLabs/urql-devtools#293]
Steps to reproduce:

```
const [res] = useQuery({
	query: <some query>,
	requestPolicy: 'cache-only'
})
```

If the query is not already cached when this hook runs, the dev tools will crash somewhere around here: https://github.com/FormidableLabs/urql-devtools/blob/ac1f04c4c83c0ecf32c9439188e48cef6a5b9919/src/panel/context/Explorer/ast/index.ts#L132-L137

because `data` will be null.

`urql` itself handles this fine – it just returns null as expected.

**Comment by andyrichardson** [comment]
Hey @vitosamson, thanks for the report :+1:

@Rigellute has gone ahead and fixed this! I'll see if we can get a patch update out some time this week.

**Comment by vitosamson** [comment]
Excellent, thanks all.
