### ISSUE TITLE
[Linux] Electron standalone app does not connect with React Native

### ISSUE THREAD

**Issue by Svarto** [FormidableLabs/urql-devtools#315]
Hi all,
I am using PopOS, Linux, and programming React Native through VSCode and running my dev app through the Android Studio emulator. I can't get the Electron urql-devtools to work. It works when I program on MacOS through the Xcode emulator, but not on Linux + Android Studio. I only get:

![Screenshot from 2020-10-02 09-26-40](https://user-images.githubusercontent.com/24279217/94898170-a249c280-0480-11eb-83f0-27308b7955da.png)

Is there any way to debugg to see what is going wrong?

The client setup (minified to improve readability, e.g. not including cache):

```
import { createClient, dedupExchange, fetchExchange } from "urql";
import { devtoolsExchange } from "@urql/devtools";


export const urqlclient = createClient({
  exchanges: [devtoolsExchange, dedupExchange, urqlcache, fetchExchange],
  url: graphqlUrl,
  fetchOptions: () => {
    const token = auth.getJWTToken();
    console.log(token ? `Bearer ${token}` : "");
    return {
      headers: { authorization: token ? `Bearer ${token}` : "" },
    };
  },
});
```

**Comment by bkonkle** [comment]
I'm using Ubuntu 20.04 - I'll see if I can reproduce. :+1:

**Comment by bkonkle** [comment]
I got sidetracked installing all things Java and Android Studio today - will circle back to this tomorrow or Thursday. :+1:

**Comment by andyrichardson** [comment]
@Svarto it's a stab in the dark but give this a shot

```sh
unset port
npx urql-devtools 
```

**Comment by bkonkle** [comment]
After some investigation, we've tracked the issue down to the usage of `localhost` in `@urql/devtools`. On Mac, `localhost` routes to the host machine. On Linux, `localhost` routes to the emulated device itself. We're researching workarounds.

**Comment by bkonkle** [comment]
@Svarto After some experimentation, it seems like the best solution is to use reverse port forwarding with the `adb` utility:

```sh
adb reverse tcp:7700 tcp:7700
```
This forwards port 7700 on the emulated device to port 7700 on the local machine, where the Electron process is listening.

Let me know if this resolves the issue for you!

**Comment by Svarto** [comment]
@bkonkle @andyrichardson thanks a lot both! It is working now perfectly!!
