### ISSUE TITLE
Add in changelog / changelog automation

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#32]
I've been using [github changelog generator](https://github.com/github-changelog-generator/github-changelog-generator) for [Tipple's changelog](https://github.com/andyrichardson/tipple/blob/master/CHANGELOG.md) which has proven to be a pretty decent option.

Alternate tools can also be used but we should have our changelog auto-generated.

**Comment by JoviDeCroock** [comment]
Should we move this issue to the exchange repo?

**Comment by andyrichardson** [comment]
@JoviDeCroock yeah I think we can do this on both repos!
