### ISSUE TITLE
Replace Operation.operationName usage with Operation.kind

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#320]
## About

See [this issue here](https://github.com/FormidableLabs/urql-devtools-exchange/issues/105).

As it's practically impossible to prevent browser extension updates, we should hold off on making this change for a while to give folks the chance to update their urql client.

**Comment by kitten** [comment]
Fixed by: https://github.com/FormidableLabs/urql-devtools-exchange/pull/108
