### ISSUE TITLE
[Runtime error]: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by menna-mostafa** [FormidableLabs/urql-devtools#323]
## About
A runtime error occurred.

## Reproduction

open inspector -> urql . It shows up the following error

<img width="757" alt="Screen Shot 2020-11-21 at 7 37 59 PM" src="https://user-images.githubusercontent.com/70471754/99883575-13ac2300-2c31-11eb-9bd6-2c4778320e46.png">

## Stack trace

```
TypeError: Cannot convert object to primitive value
    at o (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:77853)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:78576
    at Array.map (<anonymous>)
    at chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:78373
    at Array.map (<anonymous>)
    at Uc (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:8:78068)
    at qo (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1041137)
    at gs (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1087376)
    at cu (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079924)
    at su (chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js:2:1079849)
```

**Comment by andyrichardson** [comment]
Hey @menna-mostafa, thanks for the report.

Can you please provide an example repo if possible so we can reproduce the issue and work out the source of the problem.

**Comment by nik-lampe** [comment]
I have the same problem. 
And managed to track down the problem in my case.

I have typeDefs like this:
```
type Query {
  hello(name: String): String!
  breakingHello(
    name: String
    duration: DurationInput = { months: 1 }
  ): String!
}

input DurationInput {
  days: Int
  weeks: Int
  months: Int
  years: Int
}
````

And it looks like the parser trips on the default parameter definition of the breakingHello query.
When I remove it, it works. 

I hope this helps

**Comment by andyrichardson** [comment]
Hy Nik, thanks for the additional info!

I've just [tried out your example](https://codesandbox.io/s/jolly-firefly-priej?file=/src/index.js) and it looks to work fine on the version of GraphQL we are using so I'm unsure there's anything wrong with the schema itself.

**Comment by nik-lampe** [comment]
I am sorry, I don't quite know which stack trace you mean?

The output of the dev tools of the dev tools?
It's the same as in the initial comment:

```
main.js:1 Main._createAppUI: 18.963134765625 ms
main.js:1 Main._showAppUI: 11.62109375 ms
main.js:1 Main._initializeTarget: 8.620849609375 ms
main.js:1 Main._lateInitialization: 10.12890625 ms
panel.js:8 undefined
panel.js:2 TypeError: Cannot convert object to primitive value
    at o (panel.js:8)
    at panel.js:8
    at Array.map (<anonymous>)
    at panel.js:8
    at Array.map (<anonymous>)
    at Uc (panel.js:8)
    at qo (panel.js:2)
    at gs (panel.js:2)
    at cu (panel.js:2)
    at su (panel.js:2)
es @ panel.js:2
DevTools failed to load SourceMap: Could not load content for chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/prism-panel.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/panel.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/devtools.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
````

Don't know if this helps though... If there is anything else, let me know

**Comment by andyrichardson** [comment]
That's the one ☝️ 

The example schema you showed, that was from your backend? Or did you put it in the devtools UI?

**Comment by nik-lampe** [comment]
It's from my backend.

But you can recreate it easily. Here is a repo you can just clone and run.

https://github.com/nik-lampe/urql-devtools-error

Hope this helps

**Comment by andyrichardson** [comment]
You sir, are a legend 🙇 

Thanks, I'll take a look at this some time soon!

**Comment by andyrichardson** [comment]
Quick update on this - the issue was because we weren't prepared for a `defaultArgs` value that is an object.

At render time, React would throw because the object needs to be serialised.

```tsx
// This is fine
const MyComponent = () => <p>{"Hello"}</p>
// This is also fine
const MyComponent = () => <p>{"1234"}</p>
// This errors
const MyComponent = () => <p>{{ id: 1234 }}</p>
```

For the time being, we're going to stringify that defaultArgs value which will look something like this.

![Screenshot 2021-03-18 at 11 12 20](https://user-images.githubusercontent.com/10779424/111617798-7d9d9900-87db-11eb-870e-63f1fd2edbc0.png)

Expect a patch release coming through soon 👍

**Comment by andyrichardson** [comment]
I've also created a feature issue for syntax highlighting of those default objects if anyone is up for the challenge - #342
