### ISSUE TITLE
Update bug report template on runtime error

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#340]
# About

Update [bug report template](https://github.com/FormidableLabs/urql-devtools/blob/master/src/panel/pages/error/ErrorBoundary.tsx#L65) on the error boundary.

 - For browser environments, we want to [use this template](https://github.com/FormidableLabs/urql-devtools/blob/master/.github/ISSUE_TEMPLATE/bug_report_extension.md)
  - For standalone/electron environments, we want to [use this template](https://github.com/FormidableLabs/urql-devtools/blob/master/.github/ISSUE_TEMPLATE/bug_report_standalone.md)

# Additional info

The default template doesn't have a spot for stack traces - feel free to slot this in wherever you see fit!

**Comment by ValGeorgiev** [comment]
I am closing this as resolved
