### ISSUE TITLE
Code blocks don't clean up when code content changes

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#351]
# About

We [added async syntax highlighting](https://github.com/FormidableLabs/urql-devtools/blob/master/src/panel/components/CodeHighlight.tsx#L52) to address performance issues. 

That has addressed the perf issues, but it looks to have introduced a bug.

![Kapture 2021-04-21 at 16 16 13](https://user-images.githubusercontent.com/10779424/115578815-83483c00-a2bd-11eb-903d-ff0fe6088add.gif)

The code block cleans up on unmount, but not when the code (passed via props) changes while the component is mounted. This causes the old code to overlap with the new code.

I'm guessing the issue is [due to this statement](https://github.com/FormidableLabs/urql-devtools/blob/master/src/panel/components/CodeHighlight.tsx#L49)

**Comment by ValGeorgiev** [comment]
This will be fixed with the next release!
