### ISSUE TITLE
Feature to list the used exchanges and inspect the states

### ISSUE THREAD

**Issue by sharmapukar217** [FormidableLabs/urql-devtools#396]
It will be very useful if the devtool has the features to get the exchanges used

**Comment by andyrichardson** [comment]
Hey @sharmapukar217 do you have an example of what you would use this for?

**Comment by sharmapukar217** [comment]
the main is to know what exchanges am i using and how it is affecting the fetch flow. For example, inspect auth exchange to know the auth flow

**Comment by andyrichardson** [comment]
> to know what exchanges am i using

I'm not too sure about this - exchanges are typically consistent so I'm struggling to see how devtools would provide more value than, for example, looking at the code to see what exchanges are passed to the client. 

> how it is affecting the fetch flow

This I can help you with! There's an [API for dispatching events](https://formidable.com/open-source/urql/docs/advanced/debugging/#adding-your-own-debug-events) which any exchange can make use of to provide information about events (such as state changes).

Unfortunately, it looks like the [auth exchange](https://github.com/FormidableLabs/urql/blob/main/exchanges/auth/src/authExchange.ts) isn't making use of it.

It might be worth making an issue on [this repo](https://github.com/FormidableLabs/urql) identifying some key events that users of the exchange might want to know about (tokenExpiry, tokenRefreshStart, tokenRefreshComplete, etc).

From there, you should be able to get a PR going to start dispatching them in the exchange 👍

**Comment by sharmapukar217** [comment]
That would work for me
