### ISSUE TITLE
to support adding headers when sending the introspection query

### ISSUE THREAD

**Issue by Albert-Gao** [FormidableLabs/urql-devtools#398]
Hi

the introspection query to the server is failing, because the whole endpoint is protected, is there anyway we can add  the support of adding headers when sending the introspection query? thanks :)

or if we can support local schema #397  , that this feature would not be needed :)

**Comment by andyrichardson** [comment]
Hey @Albert-Gao, thanks for opening this.

Having the ability to pass the schema to the exchange (like with the cache exchange) sounds like a useful feature 👍

RE adding headers, you could add an exchange just before the fetch exchange which adds headers to the fetchOptions object. This would ensure introspection requests triggered by any exchange would have the headers included

**Comment by andyrichardson** [comment]
I'm going to close this because an intercepting exchange could do the job (drop a comment if you need help with this).

Will keep #397 around - open to contributions 👍
