### ISSUE TITLE
chrome plugin: google returns Error 404 not found!

### ISSUE THREAD

**Issue by QuaduxIT** [FormidableLabs/urql-devtools#407]
# About

Installation of the chrome plugin:
google returns Error 404 not found!

**Comment by QuaduxIT** [comment]
Is the same as:  ["Is the chrome extension still active? #408"](https://github.com/urql-graphql/urql-devtools/issues/408)

**Comment by sychovSaveliy** [comment]
Still doesn't work

**Comment by Eigilak** [comment]
Sammme
