### ISSUE TITLE
Throwing errors in console

### ISSUE THREAD

**Issue by levrik** [FormidableLabs/urql-devtools#57]
![image](https://user-images.githubusercontent.com/9491603/63687329-919e3600-c804-11e9-9d5c-362c52646758.png)

I just set it up and it's showing this in the console.

`@urql/devtools` 0.0.3
`devtools` 0.0.3
`urql` 1.4.0

**Comment by JoviDeCroock** [comment]
Hey @levrik 

I've checked out my branches locally and it seems we have to publish a new version of the chrome extension itself. We'll make work of this, thanks for bringing this to our attention. Highly appreciated.

**Comment by andyrichardson** [comment]
This is due to how we previously triggered our content script. This is nothing to worry about - just annoying to see.

The next release will have this fixed :+1:
