### ISSUE TITLE
[v0.0.4] Installation not possible due to missing asset

### ISSUE THREAD

**Issue by hiasinho** [FormidableLabs/urql-devtools#74]
### Version affected

v0.0.4

### Steps to reproduce

1. Go to the urql devtools chrome webstore
2. Click "Add to Chrome"

### Error message

An error has occurred
Package is invalid. Details: 'Could not load extension icon 'assets/icon-16.png'.'.

### Screenshot

![image](https://user-images.githubusercontent.com/489088/66866431-92984c00-ef99-11e9-9a7b-4a6c2339b1c4.png)

**Comment by andyrichardson** [comment]
Thanks for this report @hiasinho we're aware of the issue and will have a fix by the end of today :+1:

**Comment by andyrichardson** [comment]
This is now fixed with v0.5.0
