### ISSUE TITLE
Add page-action icon to Firefox

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#89]
The status icon in Chrome which shows when devtools is available or not does not show in Firefox.

See #36 for more detail on what the icon does.

**Comment by r281GQ** [comment]
That seems to be working for me.

This is a route in an app that does not have urql as a HOC.

![route wo urql](https://user-images.githubusercontent.com/21194669/97915531-84a29e00-1d49-11eb-8e25-481a3e6c199a.png)

And here is a route that has, icon not greyed out.


![route w urql](https://user-images.githubusercontent.com/21194669/97915559-92582380-1d49-11eb-8655-6f48fdd1154d.png)

The other icon there was just an experiment with `pageAction` API to see how chrome and firefox API differs.

**Comment by andyrichardson** [comment]
@r281GQ thanks for checking this - I'll close it in that case :+1:
